package com.perrigogames.life4.feature.ladder

val why = listOf(
    UILadderDetailItem(leftText = "BRILLIANT 2U", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BRILLIANT 2U(Orchestra Groove)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "DYNAMITE RAVE", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "0.59", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "B4U", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BURNIN' THE FLOOR", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "CAN'T STOP FALLIN' IN LOVE", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "HYSTERIA", rightText = "NAOKI 190", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "LEADING CYBER", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "LOVE AGAIN TONIGHT～For Melissa MIX～", rightText = "NAOKI feat. PAULA TERRY", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "ABSOLUTE", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Abyss", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BROKEN MY HEART", rightText = "NAOKI feat. PAULA TERRY", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "CAN'T STOP FALLIN' IN LOVE ～SPEED MIX～", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "INSERTiON", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "STILL IN MY HEART", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "B4U(B4 ZA BEAT MIX)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BRE&forall;K DOWN！", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BURNIN' THE FLOOR(BLUE FIRE mix)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "D2R", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "DESTINY", rightText = "NAOKI feat. PAULA TERRY", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "STILL IN MY HEART(MOMO MIX)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "革命", rightText = "dj TAKA with NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "1998", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Colors ～for EXTREME～", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Frozen Ray ～for EXTREME～", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "HYPER EUROBEAT", rightText = "NAOKI feat. DDR ALL STARS", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "KISS KISS KISS", rightText = "NAOKI feat. SHANTI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Kiss me all night long", rightText = "NAOKI J-STYLE feat.MIU", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "L'amour et la libert&eacute;(DDR Ver.)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "TEARS", rightText = "NAOKI underground feat.EK", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "蒼い衝動 ～for EXTREME～", rightText = "NAOKI feat.YUKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "CAN'T STOP FALLIN' IN LOVE -super euro version-", rightText = "NAOKI with Y&Co.", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "LOGICAL DASH", rightText = "DJ TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "MARIA(I believe...)", rightText = "NAOKI feat. PAULA TERRY", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "MOON", rightText = "dj TAKA feat.Erika", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "My Only Shining Star", rightText = "NAOKI feat. Becky Lucinda", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "PASSION OF LOVE", rightText = "NAOKI feat. PAULA TERRY", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Quickening", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "rainbow flyer", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "RED ZONE", rightText = "Tatsh&NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "STARS☆☆☆(2nd NAOKI's style)", rightText = "TЁЯRA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Tomorrow Perfume", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "B4U (&quot;VOLTAGE&quot; Special)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BRILLIANT 2U (&quot;STREAM&quot; Special)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "D2R (&quot;FREEZE&quot; Special)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "DYNAMITE RAVE (&quot;AIR&quot; Special)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Freeway Shuffle", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "L'amour et la libert&eacute;(Darwin &amp; DJ Silver remix)", rightText = "NAOKI in the MERCURE", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Poseidon", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "A Geisha's Dream", rightText = "NAOKI feat. SMiLE.dk", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Blue Rain", rightText = "dj TAKA VS Ryu☆", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "INTO YOUR HEART (Ruffage remix)", rightText = "NAOKI feat.YASMINE", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "will", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "革命(X-Special)", rightText = "dj TAKA with NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "A Brighter Day", rightText = "NAOKI feat. Aleisha G", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "All My Love", rightText = "kors k feat.ЯIRE", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Decade", rightText = "kors k Vs. dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "dirty digital", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "DROP", rightText = "dj TAKA feat.Kanako Hoshino", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Gotta Dance", rightText = "NAOKI feat. Aleisha G", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "oarfish", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Poseidon(kors k mix)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "resonance", rightText = "NAOKI-EX", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "smooooch･&forall;･", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "You are a Star", rightText = "NAOKI feat. Anna Kaelin", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Your Angel", rightText = "DM Ashura feat. kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Programmed Universe", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "HEARTBREAK (Sound Selektaz remix)", rightText = "NAOKI feat. Becca Hossany", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Let's Get Away", rightText = "NAOKI feat. Brenda Burch", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Rescue Me", rightText = "NAOKI feat. Fracus", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "SigSig", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "message", rightText = "dj TAKA feat.flare", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "osaka EVOLVED -毎度、おおきに！- (TYPE1)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "osaka EVOLVED -毎度、おおきに！- (TYPE2)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "osaka EVOLVED -毎度、おおきに！- (TYPE3)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "tokyoEVOLVED (TYPE1)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "tokyoEVOLVED (TYPE2)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "tokyoEVOLVED (TYPE3)", rightText = "NAOKI underground", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "BRILLIANT 2U (AKBK MIX)", rightText = "NAOKI", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Desert Journey", rightText = "dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Monkey Business", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Elemental Creation", rightText = "dj TAKA meets DJ YOSHITAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "The Wind of Gold", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "True Blue", rightText = "dj TAKA feat.AiMEE", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "IX", rightText = "dj TAKA VS DJ TOTTO feat.藍", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "8000000", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Poochie", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Special One", rightText = "kors k feat. Suzuyo Miyamoto", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Far east nightbird kors k Remix -DDR edit ver-", rightText = "猫叉Master", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Triple Counter", rightText = "DJ YOSHITAKA meets dj TAKA", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "朧 (dj TAKA Remix)", rightText = "HHH×MM×ST", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Trill auf G", rightText = "\"BEMANI Sound Team \"\"dj TAKA\"\"\"", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Last Card", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "DANCERUSH STARDOM ANTHEM", rightText = "kors k feat.福島蘭世", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Jetcoaster Windy", rightText = "\"BEMANI Sound Team \"\"dj TAKA\"\" feat.のの\"", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Uh-Oh", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Triple Cross", rightText = "\"BEMANI Sound Team \"\"dj TAKA & DJ YOSHITAKA & SYUNN\"\"\"", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Pump Pump Pump", rightText = "kors k", leftWeight = 0.6f, rightWeight = 0.4f),
    UILadderDetailItem(leftText = "Let's DANCE aROUND!!", rightText = "kors k feat.Jaejun by NuevoStudio", leftWeight = 0.6f, rightWeight = 0.4f),
)