package com.perrigogames.life4

object SettingsKeys {
    const val KEY_INIT_STATE = "KEY_INIT_STATE"
    const val KEY_MAJOR_UPDATE = "major_update"
    const val KEY_LAST_MOTD = "last_motd"

    const val KEY_INFO_NAME = "KEY_INFO_NAME"
    const val KEY_INFO_RANK = "KEY_INFO_RANK"
    const val KEY_INFO_TARGET_RANK = "KEY_INFO_TARGET_RANK"
    const val KEY_INFO_RIVAL_CODE = "KEY_INFO_RIVAL_CODE"
    const val KEY_INFO_SOCIAL_NETWORKS = "KEY_INFO_SOCIAL_NETWORKS"
    const val KEY_ENABLE_DIFFICULTY_TIERS = "KEY_ENABLE_DIFFICULTY_TIERS"
    const val KEY_SONG_LIST_FILTER_STATE = "KEY_SONG_LIST_FILTER_STATE"
    const val KEY_SHOW_REMOVED_SONGS = "KEY_SHOW_REMOVED_SONGS"

    const val KEY_SANBAI_DATA_REFRESHED = "KEY_SANBAI_DATA_REFRESHED"
    const val KEY_SANBAI_BEARER_TOKEN = "KEY_SANBAI_BEARER_TOKEN"
    const val KEY_SANBAI_REFRESH_TOKEN = "KEY_SANBAI_REFRESH_TOKEN"
    const val KEY_SANBAI_REFRESH_EXPIRES = "KEY_SANBAI_REFRESH_EXPIRES"
    const val KEY_SANBAI_PLAYER_ID = "KEY_SANBAI_PLAYER_ID"

    const val KEY_TRIAL_LIST_TINT_COMPLETED = "KEY_TRIAL_LIST_TINT_COMPLETED"
    const val KEY_TRIAL_LIST_SHOW_EX = "KEY_TRIAL_LIST_SHOW_EX"
    const val KEY_TRIAL_LIST_HIGHLIGHT_NEW = "KEY_TRIAL_LIST_HIGHLIGHT_NEW"
    const val KEY_TRIAL_LIST_HIGHLIGHT_UNPLAYED = "KEY_TRIAL_LIST_HIGHLIGHT_UNPLAYED"
}
